#%RAML 1.0
title: student
version: v1

mediaType: 
 - application/json

types:
  student: !include studentDataType.raml
 
/students:
 get:
  responses:
    200:
     body:
       type: any
       examples:
         output: !include studentResponse.raml
 post:
  body:
   type: student
   examples:
     input: !include studentnNoIdRequest.raml
  responses:
    200:
     body:
      examples:
        messeges: student information inserted in DB
      

          